services:
  database:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: starter
      POSTGRES_USER: starter
      POSTGRES_PASSWORD: starter-dev-password
    ports:
      - 5432:5432
    volumes:
      - psql-data:/var/lib/postgresql/data
  mailer:
    image: axllent/mailpit:v1.25
    ports:
      - 1025:1025
      - 8025:8025

  telemetry:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    environment:
      ASPIRE_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
      - 18888:18888
      - 4317:18889
      - 4318:18890

volumes:
  psql-data:
