services:
  mailer:
    image: axllent/mailpit:v1.25
    ports:
      - 1025:1025
      - 8025:8025

  telemetry:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    environment:
      ASPIRE_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
      - 18888:18888
      - 4317:18889
      - 4318:18890
