<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Starter.Application/Starter.Application.csproj" />
    <ProjectReference Include="../Starter.Domain/Starter.Domain.csproj" />
  </ItemGroup>

</Project>
